services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'gmop'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3309:3306'
  app:
    environment:
      DJANGO_SETTINGS_MODULE: 'gmop.settings.dev'
      DATABASE_URL: 'mysql://test:test@db:3306/gmop'
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8000:80"
    depends_on:
      - db
    command: sleep 286592386593
