version: '3.4'
services:
  gmop_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'gmop'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./gmop_data:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: bridge

