apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    mars: microservise
    find: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80