# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: httpd
        ports:
        - 3306:80
        # options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: example
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
         curl httpd